
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EAnimState
    {
        BalloonFlyingDown = 0,
        BalloonFlyingLoop = 1,
        BalloonFlyingUp = 2,
        BalloonIn = 3,
        BalloonOut = 4,
        DearIdol = 5,
        DearJump = 6,
        DearSmile = 7,
        EatJun = 8,
        EatNormal = 9,
        FriendHightouch = 10,
        ManaIdle = 11,
        ManaJump = 12,
        NoWeaponIdle = 13,
        NoWeaponJoyShort = 14,
        NoWeaponRun = 15,
        NoWeaponRunSuper = 16,
        RunHighJump = 17,
        RunJump = 18,
        RunSpringJump = 19,
        Smile = 20,
        StaminaKarinOjigi = 21,
        UnitRaceEatShaveice = 22,
        UnitRaceRunCarpet = 23,
        UnitRaceSurfing = 24,
        UnitRaceSurfingIn = 25,
        UnitRaceSurfingOut = 26,
        UnitRaceSurfingUp = 27,
        Attack = 28,
        AttackSkipQuest = 29,
        Damage = 30,
        Die = 31,
        Idle = 32,
        JoyLong = 33,
        JoyLongReturn = 34,
        JoyShort = 35,
        JoyShortReturn = 36,
        Landing = 37,
        MultiIdleNoWeapon = 38,
        MultiIdleStandBy = 39,
        MultiStandBy = 40,
        Run = 41,
        RunGamestart = 42,
        StandBy = 43,
        Walk = 44,
        JoyResult = 45,
        Skill0 = 46,
        Skill1 = 47,
        Skill2 = 48,
        SkillEvolution0 = 49,
    }

} 

