
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public TAnim TAnim {get; }
    public TPrincessCard TPrincessCard {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TAnim = new TAnim(loader("tanim"));
        TPrincessCard = new TPrincessCard(loader("tprincesscard"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TAnim.ResolveRef(this);
        TPrincessCard.ResolveRef(this);
    }
}

}
