
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class VPrincessCard : Luban.BeanBase
{
    public VPrincessCard(ByteBuf _buf) 
    {
        PrincessType = (EPrincessType)_buf.ReadInt();
        CoolDown = _buf.ReadFloat();
        MaxCoolDown = _buf.ReadFloat();
        Cost = _buf.ReadInt();
    }

    public static VPrincessCard DeserializeVPrincessCard(ByteBuf _buf)
    {
        return new VPrincessCard(_buf);
    }

    public readonly EPrincessType PrincessType;
    public readonly float CoolDown;
    public readonly float MaxCoolDown;
    public readonly int Cost;
   
    public const int __ID__ = -1836968049;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "PrincessType:" + PrincessType + ","
        + "CoolDown:" + CoolDown + ","
        + "MaxCoolDown:" + MaxCoolDown + ","
        + "Cost:" + Cost + ","
        + "}";
    }
}

}
